/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.coordinatorlayout;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f040027;
        public static final int coordinatorLayoutStyle = 0x7f0400a7;
        public static final int font = 0x7f0400fa;
        public static final int fontProviderAuthority = 0x7f0400fc;
        public static final int fontProviderCerts = 0x7f0400fd;
        public static final int fontProviderFetchStrategy = 0x7f0400fe;
        public static final int fontProviderFetchTimeout = 0x7f0400ff;
        public static final int fontProviderPackage = 0x7f040100;
        public static final int fontProviderQuery = 0x7f040101;
        public static final int fontStyle = 0x7f040102;
        public static final int fontVariationSettings = 0x7f040103;
        public static final int fontWeight = 0x7f040104;
        public static final int keylines = 0x7f040132;
        public static final int layout_anchor = 0x7f040137;
        public static final int layout_anchorGravity = 0x7f040138;
        public static final int layout_behavior = 0x7f040139;
        public static final int layout_dodgeInsetEdges = 0x7f040165;
        public static final int layout_insetEdge = 0x7f04016e;
        public static final int layout_keyline = 0x7f04016f;
        public static final int statusBarBackground = 0x7f0401d0;
        public static final int ttcIndex = 0x7f040232;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f06007a;
        public static final int notification_icon_bg_color = 0x7f06007b;
        public static final int ripple_material_light = 0x7f060086;
        public static final int secondary_text_default_material_light = 0x7f060088;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f070050;
        public static final